### ISSUE TITLE
Internal server error with real DSR data.

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-datahub#193]
**Describe the bug**
After POSTing the DSR data successfully. The GET method returns an Internal Server Error 

```python
Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
     result = await app(  # type: ignore[func-returns-value]
   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
     return await self.app(scope, receive, send)
   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
     await super().__call__(scope, receive, send)
   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
     await self.middleware_stack(scope, receive, send)
   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
     raise exc
   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
     await self.app(scope, receive, _send)
   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
     raise exc
   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
     await self.app(scope, receive, sender)
   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
     raise e
   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
     await self.app(scope, receive, send)
   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
     await route.handle(scope, receive, send)
   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
     await self.app(scope, receive, send)
   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
     response = await func(request)
   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
     raw_response = await run_endpoint_function(
   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
     return await run_in_threadpool(dependant.call, **values)
   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
     return await anyio.to_thread.run_sync(func, *args)
   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
     return await get_asynclib().run_sync_in_worker_thread(
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
     return await future
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
     result = context.run(func, *args)
   File "/src/app/main.py", line 223, in get_dsr_data
     return ORJSONResponse({"data": filtered_index_data})
   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 196, in __init__
     super().__init__(content, status_code, headers, media_type, background)
   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 55, in __init__
     self.body = self.render(content)
   File "/usr/local/lib/python3.10/site-packages/fastapi/responses.py", line 46, in render
     return orjson.dumps(
 TypeError: unsupported datatype in numpy array
```

**Additional context**
This is happening with the columns that have string data - specifically the Activity Types

**Comment by AdrianDAlessandro** [comment]
Data causing this error - upload this (simplest to do it via the "Try it out" button in the datahub docs for the DSR POST)

[TestOutput_revised_noEVID.h5.zip](https://github.com/ImperialCollegeLondon/gridlington-datahub/files/13528081/TestOutput_revised_noEVID.h5.zip)
